services:
  provider_0:
    image: yagna-provider
    ports:
      - '8555:7465'
    command: golemsp run --payment-network testnet --no-interactive
    devices:
      - /dev/kvm
    env_file:
      - node_env.env
    environment:
      - NODE_NAME=dock-prov_0
      - SUBNET=change_me
    volumes:
      - './dock_prov_0/ya-provider:/root/.local/share/ya-provider'
      - './dock_prov_0/yagna:/root/.local/share/yagna'
  provider_1:
    image: yagna-provider
    ports:
      - '8556:7465'
    command: golemsp run --payment-network testnet --no-interactive
    devices:
      - /dev/kvm
    env_file:
      - node_env.env
    environment:
      - NODE_NAME=dock-prov_1
      - SUBNET=change_me
    volumes:
      - './dock_prov_1/ya-provider:/root/.local/share/ya-provider'
      - './dock_prov_1/yagna:/root/.local/share/yagna'
